# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been inactive for 60 days and is now marked as stale. It will be closed in 7 days without further activity.'
        stale-pr-message: 'This PR has been inactive for 60 days and is now marked as stale. It will be closed in 7 days without further activity.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale-PR'
