name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: hmmer
        version: 1.0
    - run: pip install -r requirements.txt
    - run: pip install coverage
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Update DefenseFinder models
      run: |
        defense-finder update
    - name: Run the tests
      run: |
        coverage run --source . tests/run_tests.py
        coverage report -m